/**
 * Design tokens, mirrored from the CSS variables in `src/index.css` (which is the
 * source of truth — these are generated by the `@theme` block there via Tailwind
 * v4). Import from here when a value is needed in JS/TS rather than a className,
 * e.g. an inline SVG fill, a chart color, or a value passed to a native API.
 *
 * See THEME.md for where each value was pulled from in Figma.
 */

export const color = {
  background: "#fffbf5",
  surface: "#f5efe4",
  ink: "#422f0e",
  inkSoft: "#a6a69e",
  accent: "#3d202b",
  accentSoft: "#c29cac",
} as const

/** Card color variants — bg/fg pairs, see Card.tsx `color` prop. */
export const cardColor = {
  wasabi: { bg: "#e0e939", fg: "#484800" },
  coolBlue: { bg: "#ceeaf5", fg: "#32586a" },
  sage: { bg: "#adb9a2", fg: "#2f3a27" },
  orange: { bg: "#ff663a", fg: "#841200" },
} as const

export type CardColorName = keyof typeof cardColor

export const font = {
  display: "'Outfit', ui-sans-serif, system-ui, sans-serif",
  sans: "'Plus Jakarta Sans', ui-sans-serif, system-ui, sans-serif",
} as const

export const radius = {
  card: "24px",
  photo: "16px",
  pill: "9999px",
  tabbar: "30px",
} as const

export const spacing = {
  screenX: "18px",
  headerX: "22px",
  tabbarX: "14px",
} as const

export const shadow = {
  float: "0px 10px 17px rgba(20, 22, 26, 0.13), 0px 2px 3px rgba(20, 22, 26, 0.05)",
} as const
